name: Test
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn typecheck
      - run: yarn lint:nofix
      - run: echo "VITE_API_URL=http://localhost:3000" > .env
      - run: yarn build
      - run: yarn test:e2e
